name = "FloppaLand"
author = "Zizazr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d36fec93ad7c86ed330ec040b1415a70897e037d37957f86bb700ce01047fb3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
