name = "FloppaLand"
author = "Zizazr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24cfdc579278b1309321607ae083c5e761fdf9a075621d7a431c10094f849762"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
