name = "FloppaLand"
author = "Zizazr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01436a3da70fbbfe563c53973684bc52eb61957cb62e156e0dfbac6584c900ef"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
